### ISSUE TITLE
Loading Session Panic.

### ISSUE THREAD

**Issue by acky666** [srinathgs/mysqlstore#22]
Hiya,

Loading a session causes the code to panic.   

`2020/04/13 23:35:47 http: panic serving 127.0.0.1:64951: interface conversion: driver.Value is time.Time, not []uint8
goroutine 103 [running]:
net/http.(*conn).serve.func1(0xc0001c2a00)
        /usr/local/Cellar/go/1.13.7/libexec/src/net/http/server.go:1767 +0x139
panic(0x1410420, 0xc000117170)
        /usr/local/Cellar/go/1.13.7/libexec/src/runtime/panic.go:679 +0x1b2
github.com/srinathgs/mysqlstore.(*MySQLStore).load(0xc0003c2660, 0xc0003f4500, 0xc000412367, 0x48)
        /Users/ackers/go/src/github.com/srinathgs/mysqlstore/mysqlstore.go:284 +0xa05
github.com/srinathgs/mysqlstore.(*MySQLStore).New(0xc0003c2660, 0xc000428b00, 0x1485e8a, 0x6, 0x1804460, 0xc0003ce400, 0x6)`

MySQL is version 8 running locally on my Mac.  

I fixed by changing to this..

	//sess.createdOn, _ = time.Parse(timeFormat, string(timeCreated.([]uint8)))
	//sess.modifiedOn, _ = time.Parse(timeFormat, string(timeModified.([]uint8)))
	//sess.expiresOn, _ = time.Parse(timeFormat, string(timeExpires.([]uint8)))

	sess.createdOn = timeCreated.(time.Time)
	sess.modifiedOn = timeModified.(time.Time)
	sess.expiresOn = timeExpires.(time.Time)

Thanks.

**Comment by srinathgs** [comment]
hi, with issue #23 fixed, this should not happen. can you please pull the lib again and test?
